[profile.default]
src = "src"
out = "out"
solc_version="0.8.34"
libs = ["lib"]
remappings=["@openzeppelin/contract=lib/openzeppelin-contracts"]


[invariant]
runs = 64
depth = 64
fail_on_revert = true

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# remappings = ['@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/', '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

